use llmblast::{Provider, _call_llm_batch};
use std::env;

#[tokio::main]
pub async fn main() {
    let res = _call_llm_batch(
        vec![
            "Give me a random paragraph about number 1".into(),
            "Give me a random paragraph about number 2".into(),
            "Give me a random paragraph about number 3".into(),
            "Give me a random paragraph about number 4".into(),
            "Give me a random paragraph about number 5".into(),
            "Give me a random paragraph about number 6".into(),
            "Give me a random paragraph about number 7".into(),
            "Give me a random paragraph about number 8".into(),
            "Give me a random paragraph about number 9".into(),
            "Give me a random paragraph about number 10".into(),
            "Give me a random paragraph about number 11".into(),
            "Give me a random paragraph about number 12".into(),
            "Give me a random paragraph about number 10".into(),
            "Give me a random paragraph about number 12".into(),
            "Give me a random paragraph about number 13".into(),
            "Give me a random paragraph about number 14".into(),
            "Give me a random paragraph about number 15".into(),
            "Give me a random paragraph about number 16".into(),
            "Give me a random paragraph about number 17".into(),
            "Give me a random paragraph about number 18".into(),
            "Give me a random paragraph about number 19".into(),
            "Give me a random paragraph about number 21".into(),
            "Give me a random paragraph about number 22".into(),
            "Give me a random paragraph about number 23".into(),
            "Give me a random paragraph about number 24".into(),
            "Give me a random paragraph about number 25".into(),
            "Give me a random paragraph about number 26".into(),
            "Give me a random paragraph about number 27".into(),
            "Give me a random paragraph about number 28".into(),
            "Give me a random paragraph about number 29".into(),
            "Give me a random paragraph about number 30".into(),
            "Give me a random paragraph about number 31".into(),
            "Give me a random paragraph about number 32".into(),
            "Give me a random paragraph about number 33".into(),
            "Give me a random paragraph about number 34".into(),
            "Give me a random paragraph about number 35".into(),
            "Give me a random paragraph about number 36".into(),
            "Give me a random paragraph about number 37".into(),
            "Give me a random paragraph about number 38".into(),
            "Give me a random paragraph about number 39".into(),
            "Give me a random paragraph about number 1".into(),
            "Give me a random paragraph about number 2".into(),
            "Give me a random paragraph about number 3".into(),
            "Give me a random paragraph about number 4".into(),
            "Give me a random paragraph about number 5".into(),
            "Give me a random paragraph about number 6".into(),
            "Give me a random paragraph about number 7".into(),
            "Give me a random paragraph about number 8".into(),
            "Give me a random paragraph about number 9".into(),
            "Give me a random paragraph about number 10".into(),
            "Give me a random paragraph about number 11".into(),
            "Give me a random paragraph about number 12".into(),
            "Give me a random paragraph about number 10".into(),
            "Give me a random paragraph about number 12".into(),
            "Give me a random paragraph about number 13".into(),
            "Give me a random paragraph about number 14".into(),
            "Give me a random paragraph about number 15".into(),
            "Give me a random paragraph about number 16".into(),
            "Give me a random paragraph about number 17".into(),
            "Give me a random paragraph about number 18".into(),
            "Give me a random paragraph about number 19".into(),
            "Give me a random paragraph about number 21".into(),
            "Give me a random paragraph about number 22".into(),
            "Give me a random paragraph about number 23".into(),
            "Give me a random paragraph about number 24".into(),
            "Give me a random paragraph about number 25".into(),
            "Give me a random paragraph about number 26".into(),
            "Give me a random paragraph about number 27".into(),
            "Give me a random paragraph about number 28".into(),
            "Give me a random paragraph about number 29".into(),
            "Give me a random paragraph about number 30".into(),
            "Give me a random paragraph about number 31".into(),
            "Give me a random paragraph about number 32".into(),
            "Give me a random paragraph about number 33".into(),
            "Give me a random paragraph about number 34".into(),
            "Give me a random paragraph about number 35".into(),
            "Give me a random paragraph about number 36".into(),
            "Give me a random paragraph about number 37".into(),
            "Give me a random paragraph about number 38".into(),
            "Give me a random paragraph about number 39".into(),
        ],
        Provider::OpenAI {
            model_name: String::from("gpt-4.1"),
            api_key: String::from(env::var("OPENAI_API_KEY").expect("OPENAI_API_KEY not set")),
        },
    )
    .await
    .unwrap();
    println!("{:#?}", res);
    println!("{}", res.len());
}
